---
name: Build netbox-plugins container image

permissions:
  packages: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - .github/workflows/build-netbox-plugins-container-image.yml
      - netbox-plugins/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/build-netbox-plugins-container-image.yml
      - netbox-plugins/**

jobs:
  build-netbox-plugins-container-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 3.2.0  # renovate: datasource=docker depName=netbox-community/netbox-docker
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup docker
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.repository == 'regiocloud/container-images' && github.ref == 'refs/heads/main'

      - name: Build container image
        uses: docker/build-push-action@v6
        with:
          context: images/clusterctl
          push: false
          tags: ghcr.io/regiocloud/netbox-plugins:${{ matrix.version }}
          build-args: |
            VERSION=${{ matrix.version }}
        if: github.repository == 'regiocloud/container-images' && github.ref != 'refs/heads/main'

      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          context: images/clusterctl
          push: true
          tags: ghcr.io/regiocloud/netbox-plugins:${{ matrix.version }}
          build-args: |
            VERSION=${{ matrix.version }}
        if: github.repository == 'regiocloud/container-images' && github.ref == 'refs/heads/main'
