---
name: Build netbox-plugins container image

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/build-netbox-plugins-container-image.yml
      - netbox-plugins/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/build-netbox-plugins-container-image.yml
      - netbox-plugins/**

jobs:

  build-netbox-plugins-container-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 3.2.0  # renovate: datasource=docker depName=netbox-community/netbox-docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: 'v2.2.4'

      - name: Setup docker
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/main'

      - name: Extract Container metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: regiocloud/netbox-plugins

      - name: Build and push Container image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ./netbox/
          push: ${{ github.event_name != 'pull_request' }}
          tags: regiocloud/netbox-plugins:${{ matrix.version }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
